const seed={center:{name:'مركز الشفاء الطبي',address:'قنا — شارع المثال',phone:'01000000000',hours:'السبت–الخميس: 10 ص – 10 م',branches:'فرع رئيسي'},clinics:[{id:1,name:'الجلدية',desc:'تشخيص وعلاج أمراض الجلد',price:'300'},{id:2,name:'الأطفال',desc:'متابعة وعلاج الأطفال',price:'250'},{id:3,name:'الباطنة',desc:'كشف ومتابعة الأمراض الباطنة',price:'300'},{id:4,name:'الأسنان',desc:'علاج وفحص الأسنان',price:'350'},{id:5,name:'العظام',desc:'عظام ومفاصل',price:'300'},{id:6,name:'النساء والتوليد',desc:'متابعة النساء والتوليد',price:'400'}],doctors:[{id:1,name:'د. أحمد محمد',specialty:'جلدية',days:'السبت، الإثنين، الأربعاء',time:'5 م – 9 م'},{id:2,name:'د. سارة علي',specialty:'أطفال',days:'الأحد، الثلاثاء، الخميس',time:'4 م – 8 م'}],services:[{id:1,name:'كشف جلدية',price:'300'},{id:2,name:'كشف أطفال',price:'250'}],faqs:[{id:1,q:'ما هي مواعيد العمل؟',a:'المركز يعمل من السبت إلى الخميس من 10 صباحًا حتى 10 مساءً.'},{id:2,q:'هل يوجد حجز مسبق؟',a:'نعم، يمكن طلب الحجز من خلال خدمة الاستقبال.'}]};
let db=JSON.parse(localStorage.getItem('medicalAI'))||seed;let page='dashboard';const $=s=>document.querySelector(s);const save=()=>localStorage.setItem('medicalAI',JSON.stringify(db));
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{page=b.dataset.page;document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x===b));render()});$('#saveAll').onclick=()=>{save();toast('تم حفظ البيانات بنجاح')};function toast(t){alert(t)}
function render(){let titles={dashboard:'لوحة التحكم',center:'بيانات المركز',clinics:'العيادات',doctors:'الأطباء والمواعيد',services:'الخدمات والأسعار',faqs:'الأسئلة الشائعة',chat:'تجربة الـAI'};$('#title').textContent=titles[page];let c=$('#content');({dashboard,center,clinics,doctors,services,faqs,chat}[page])(c)}
function dashboard(c){c.innerHTML=`<div class="grid"><div class="card"><span class="muted">العيادات</span><div class="stat">${db.clinics.length}</div><span class="muted">عيادة مسجلة</span></div><div class="card"><span class="muted">الأطباء</span><div class="stat">${db.doctors.length}</div><span class="muted">طبيب مسجل</span></div><div class="card"><span class="muted">الأسئلة الشائعة</span><div class="stat">${db.faqs.length}</div><span class="muted">إجابة جاهزة للـAI</span></div></div><br><div class="notice">هذه نسخة تجريبية. البيانات الحالية تجريبية، ويمكن تعديلها وحفظها محليًا. لا تدخل بيانات مرضى حقيقية في هذه النسخة.</div><div class="card"><h3>جاهز لتجربة المساعد</h3><p class="muted">ادخل إلى «تجربة الـAI» واسأل عن العيادات، الأسعار، المواعيد أو بيانات المركز.</p><button class="primary" onclick="page='chat';document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page==='chat'));render()">ابدأ التجربة</button></div>`}
function center(c){c.innerHTML=`<div class="form"><div class="fields"><div class="field"><label>اسم المركز</label><input id="cn" value="${db.center.name}"></div><div class="field"><label>رقم الهاتف</label><input id="cp" value="${db.center.phone}"></div><div class="field full"><label>العنوان</label><input id="ca" value="${db.center.address}"></div><div class="field full"><label>مواعيد العمل</label><input id="ch" value="${db.center.hours}"></div><div class="field full"><label>الفروع</label><input id="cb" value="${db.center.branches}"></div></div><br><button class="primary" onclick="db.center={name:cn.value,address:ca.value,phone:cp.value,hours:ch.value,branches:cb.value};save();toast('تم حفظ بيانات المركز')">حفظ</button></div>`}
function listPage(c,type){let arr=db[type];c.innerHTML=`<div class="section-head"><p class="muted">يمكن تعديل البيانات في أي وقت.</p><button class="primary" onclick="addItem('${type}')">+ إضافة</button></div><div class="list">${arr.map(x=>`<div class="row"><div><h3>${x.name||x.q}</h3><span class="muted">${type==='faqs'?x.a:Object.values(x).filter(v=>v&&typeof v!=='number'&&v!==x.name).join(' · ')}</span></div><div class="actions"><button class="secondary" onclick="editItem('${type}',${x.id})">تعديل</button><button class="danger" onclick="removeItem('${type}',${x.id})">حذف</button></div></div>`).join('')||'<div class="empty">لا توجد بيانات بعد</div>'}</div>`}
function clinics(c){listPage(c,'clinics')}function doctors(c){listPage(c,'doctors')}function services(c){listPage(c,'services')}function faqs(c){listPage(c,'faqs')}
function addItem(type){let vals=type==='clinics'?{name:prompt('اسم العيادة'),desc:prompt('وصف مختصر'),price:prompt('سعر الكشف')}:type==='doctors'?{name:prompt('اسم الطبيب'),specialty:prompt('التخصص'),days:prompt('أيام العمل'),time:prompt('المواعيد')}:type==='services'?{name:prompt('اسم الخدمة'),price:prompt('السعر')}: {q:prompt('السؤال'),a:prompt('الإجابة')};if(Object.values(vals).some(v=>v===null||v===''))return;vals.id=Date.now();db[type].push(vals);save();render()}
function editItem(type,id){let x=db[type].find(a=>a.id===id);if(!x)return;for(const k of Object.keys(x)){if(k==='id')continue;let v=prompt(k,x[k]);if(v===null)return;x[k]=v}save();render()}
function removeItem(type,id){if(confirm('حذف هذا العنصر؟')){db[type]=db[type].filter(x=>x.id!==id);save();render()}}
function chat(c){c.innerHTML=`<div class="chat"><div class="messages" id="msgs"><div class="msg bot">أهلًا بحضرتك. أنا المساعد الافتراضي لـ${db.center.name}. أقدر أساعدك في معرفة العيادات، الأطباء، الأسعار ومواعيد العمل.</div></div><div class="chatbar"><input id="q" placeholder="اكتب سؤالك هنا..."><button class="primary" onclick="send()">إرسال</button></div></div>`;q.onkeydown=e=>{if(e.key==='Enter')send()}}
function answer(q){q=q.toLowerCase();if(q.includes('سعر')||q.includes('كشف')||q.includes('فلوس'))return 'أسعار الكشف: '+db.clinics.map(x=>`${x.name}: ${x.price} جنيه`).join(' — ');if(q.includes('مواعيد')||q.includes('فاتح')||q.includes('عمل'))return `مواعيد المركز: ${db.center.hours}`;if(q.includes('عياد'))return 'العيادات المتاحة: '+db.clinics.map(x=>x.name).join('، ');if(q.includes('دكتور')||q.includes('طبيب'))return db.doctors.map(x=>`${x.name} — ${x.specialty} — ${x.days} — ${x.time}`).join('\n');for(const f of db.faqs)if(q.includes(f.q.slice(0,6).toLowerCase()))return f.a;return 'أقدر أساعدك في العيادات، الأطباء، الأسعار ومواعيد العمل. ولو سؤالك يحتاج موظفًا، أقدر أحوّل المحادثة للاستقبال.'}
function send(){let v=q.value.trim();if(!v)return;let m=$('#msgs');m.innerHTML+=`<div class="msg user">${escapeHtml(v)}</div><div class="msg bot">${escapeHtml(answer(v)).replaceAll('\n','<br>')}</div>`;q.value='';m.scrollTop=m.scrollHeight}function escapeHtml(s){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}render();