const seed={center:{name:'مركز الشفاء الطبي',address:'قنا — شارع المثال',phone:'01000000000',hours:'السبت–الخميس: 10 ص – 10 م',branches:'فرع رئيسي'},clinics:[{id:1,name:'الجلدية',desc:'تشخيص وعلاج أمراض الجلد'},{id:2,name:'الأطفال',desc:'متابعة وعلاج الأطفال'},{id:3,name:'الباطنة',desc:'كشف ومتابعة الأمراض الباطنة'},{id:4,name:'الأسنان',desc:'علاج وفحص الأسنان'},{id:5,name:'العظام',desc:'عظام ومفاصل'},{id:6,name:'النساء والتوليد',desc:'متابعة النساء والتوليد'}],doctors:[{id:1,name:'د. أحمد محمد',specialty:'جلدية',clinicId:1,days:'السبت، الإثنين، الأربعاء',time:'5 م – 9 م'},{id:2,name:'د. سارة علي',specialty:'أطفال',clinicId:2,days:'الأحد، الثلاثاء، الخميس',time:'4 م – 8 م'}],services:[{id:1,name:'كشف جلدية',clinicId:1,price:'300'},{id:2,name:'كشف أطفال',clinicId:2,price:'250'}],faqs:[{id:1,q:'ما هي مواعيد العمل؟',a:'المركز يعمل من السبت إلى الخميس من 10 صباحًا حتى 10 مساءً.'},{id:2,q:'هل يوجد حجز مسبق؟',a:'نعم، يمكن طلب الحجز من خلال خدمة الاستقبال.'}]};
function normalizeData(data){data=data||JSON.parse(JSON.stringify(seed));data.clinics=(data.clinics||[]).map(c=>{const {price,...clinic}=c;return clinic});data.doctors=(data.doctors||[]).map(d=>({...d,clinicId:d.clinicId||findClinicIdByName(data.clinics,d.specialty)}));data.services=(data.services||[]).map(s=>({...s,clinicId:s.clinicId||findClinicIdByName(data.clinics,s.name)}));return data}
function findClinicIdByName(clinics,text){if(!text)return clinics[0]?.id||null;const t=String(text).toLowerCase();return clinics.find(c=>t.includes(String(c.name).toLowerCase())||String(c.name).toLowerCase().includes(t))?.id||clinics[0]?.id||null}
let db=normalizeData(JSON.parse(localStorage.getItem('medicalAI'))||seed);JSON.parse(localStorage.getItem('medicalAI'))||seed;let page='dashboard';const $=s=>document.querySelector(s);const save=()=>localStorage.setItem('medicalAI',JSON.stringify(db));
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{page=b.dataset.page;document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x===b));render()});$('#saveAll').onclick=()=>{save();toast('تم حفظ البيانات بنجاح')};function toast(t){alert(t)}
function render(){let titles={dashboard:'لوحة التحكم',center:'بيانات المركز',clinics:'العيادات',doctors:'الأطباء والمواعيد',services:'الخدمات والأسعار',faqs:'الأسئلة الشائعة',chat:'تجربة الـAI'};$('#title').textContent=titles[page];let c=$('#content');({dashboard,center,clinics,doctors,services,faqs,chat}[page])(c)}
function dashboard(c){c.innerHTML=`<div class="grid"><div class="card"><span class="muted">العيادات</span><div class="stat">${db.clinics.length}</div><span class="muted">عيادة مسجلة</span></div><div class="card"><span class="muted">الأطباء</span><div class="stat">${db.doctors.length}</div><span class="muted">طبيب مسجل</span></div><div class="card"><span class="muted">الأسئلة الشائعة</span><div class="stat">${db.faqs.length}</div><span class="muted">إجابة جاهزة للـAI</span></div></div><br><div class="notice">هذه نسخة تجريبية. البيانات الحالية تجريبية، ويمكن تعديلها وحفظها محليًا. لا تدخل بيانات مرضى حقيقية في هذه النسخة.</div><div class="card"><h3>جاهز لتجربة المساعد</h3><p class="muted">ادخل إلى «تجربة الـAI» واسأل عن العيادات، الأسعار، المواعيد أو بيانات المركز.</p><button class="primary" onclick="page='chat';document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page==='chat'));render()">ابدأ التجربة</button></div>`}
function center(c){c.innerHTML=`<div class="form"><div class="fields"><div class="field"><label>اسم المركز</label><input id="cn" value="${db.center.name}"></div><div class="field"><label>رقم الهاتف</label><input id="cp" value="${db.center.phone}"></div><div class="field full"><label>العنوان</label><input id="ca" value="${db.center.address}"></div><div class="field full"><label>مواعيد العمل</label><input id="ch" value="${db.center.hours}"></div><div class="field full"><label>الفروع</label><input id="cb" value="${db.center.branches}"></div></div><br><button class="primary" onclick="db.center={name:cn.value,address:ca.value,phone:cp.value,hours:ch.value,branches:cb.value};save();toast('تم حفظ بيانات المركز')">حفظ</button></div>`}
function clinicName(id){return db.clinics.find(c=>c.id===Number(id))?.name||'غير محدد'}
function clinicOptions(selected){return db.clinics.map(c=>`<option value="${c.id}" ${Number(selected)===Number(c.id)?'selected':''}>${escapeHtml(c.name)}</option>`).join('')}
function listPage(c,type){let arr=db[type];c.innerHTML=`<div class="section-head"><p class="muted">يمكن تعديل البيانات في أي وقت.</p><button class="primary" onclick="addItem('${type}')">+ إضافة</button></div><div class="list">${arr.map(x=>`<div class="row"><div><h3>${escapeHtml(x.name||x.q)}</h3><span class="muted">${type==='faqs'?escapeHtml(x.a):type==='doctors'?escapeHtml(`${x.specialty} · ${clinicName(x.clinicId)} · ${x.days} · ${x.time}`):type==='services'?escapeHtml(`${clinicName(x.clinicId)} · ${x.price} جنيه`):escapeHtml(x.desc)}</span></div><div class="actions"><button class="secondary" onclick="editItem('${type}',${x.id})">تعديل</button><button class="danger" onclick="removeItem('${type}',${x.id})">حذف</button></div></div>`).join('')||'<div class="empty">لا توجد بيانات بعد</div>'}</div>`}
function clinics(c){listPage(c,'clinics')}function doctors(c){listPage(c,'doctors')}function services(c){listPage(c,'services')}function faqs(c){listPage(c,'faqs')}
function openModal(type,id=null){const existing=id?db[type].find(x=>x.id===id):null;const modal=document.createElement('div');modal.className='modal-backdrop';modal.id='dataModal';modal.innerHTML=`<div class="modal" role="dialog" aria-modal="true"><div class="modal-head"><div><h2>${id?'تعديل':'إضافة'} ${type==='clinics'?'عيادة':type==='doctors'?'طبيب':type==='services'?'خدمة':'سؤال شائع'}</h2><p class="muted">أدخل البيانات المطلوبة ثم اضغط حفظ.</p></div><button class="icon-btn" onclick="closeModal()">×</button></div><form id="dataForm" onsubmit="submitModal(event,'${type}',${id||'null'})">${formFields(type,existing)}</form></div>`;document.body.appendChild(modal);setTimeout(()=>modal.querySelector('input,select,textarea')?.focus(),0)}
function formFields(type,x){x=x||{};if(type==='clinics')return `<div class="fields"><div class="field full"><label>اسم العيادة</label><input name="name" required value="${escapeAttr(x.name)}"></div><div class="field full"><label>وصف مختصر</label><textarea name="desc" required>${escapeHtml(x.desc||'')}</textarea></div></div><div class="doctor-builder"><div class="builder-head"><div><h3>أطباء العيادة</h3><span class="muted">أضف كل طبيب وتخصصه والأيام والمواعيد التي يعمل فيها بالمركز.</span></div><button type="button" class="secondary" onclick="addDoctorRow()">+ إضافة طبيب</button></div><div id="doctorRows"></div></div><div class="modal-actions"><button type="button" class="secondary" onclick="closeModal()">إلغاء</button><button class="primary">حفظ العيادة</button></div>`;
if(type==='doctors')return `<div class="fields"><div class="field"><label>اسم الطبيب</label><input name="name" required value="${escapeAttr(x.name)}"></div><div class="field"><label>التخصص</label><input name="specialty" required value="${escapeAttr(x.specialty)}"></div><div class="field full"><label>العيادة</label><select name="clinicId" required>${clinicOptions(x.clinicId)}</select></div><div class="field"><label>أيام العمل</label><input name="days" required value="${escapeAttr(x.days)}"></div><div class="field"><label>المواعيد</label><input name="time" required value="${escapeAttr(x.time)}"></div></div><div class="modal-actions"><button type="button" class="secondary" onclick="closeModal()">إلغاء</button><button class="primary">حفظ الطبيب</button></div>`;
if(type==='services')return `<div class="fields"><div class="field"><label>اسم الخدمة</label><input name="name" required value="${escapeAttr(x.name)}"></div><div class="field"><label>السعر (جنيه)</label><input name="price" type="number" min="0" required value="${escapeAttr(x.price)}"></div><div class="field full"><label>العيادة</label><select name="clinicId" required>${clinicOptions(x.clinicId)}</select></div></div><div class="modal-actions"><button type="button" class="secondary" onclick="closeModal()">إلغاء</button><button class="primary">حفظ الخدمة</button></div>`;
return `<div class="fields"><div class="field full"><label>السؤال</label><input name="q" required value="${escapeAttr(x.q)}"></div><div class="field full"><label>الإجابة</label><textarea name="a" required>${escapeHtml(x.a||'')}</textarea></div></div><div class="modal-actions"><button type="button" class="secondary" onclick="closeModal()">إلغاء</button><button class="primary">حفظ السؤال</button></div>`}
function addDoctorRow(data={}){const box=document.getElementById('doctorRows');if(!box)return;const row=document.createElement('div');row.className='doctor-row';row.innerHTML=`<div class="fields"><div class="field"><label>اسم الدكتور</label><input class="d-name" required value="${escapeAttr(data.name)}"></div><div class="field"><label>التخصص</label><input class="d-specialty" required value="${escapeAttr(data.specialty)}"></div><div class="field full"><label>أيام العمل في المركز</label><input class="d-days" required placeholder="مثال: السبت، الإثنين، الأربعاء" value="${escapeAttr(data.days)}"></div><div class="field"><label>من الساعة</label><input class="d-from" type="time" required value="${escapeAttr(data.from||'17:00')}"></div><div class="field"><label>إلى الساعة</label><input class="d-to" type="time" required value="${escapeAttr(data.to||'21:00')}"></div></div><button type="button" class="danger remove-doctor" onclick="this.closest('.doctor-row').remove()">حذف الطبيب</button>`;box.appendChild(row)}
function collectDoctorRows(){return [...document.querySelectorAll('.doctor-row')].map(row=>({name:row.querySelector('.d-name').value.trim(),specialty:row.querySelector('.d-specialty').value.trim(),days:row.querySelector('.d-days').value.trim(),from:row.querySelector('.d-from').value,to:row.querySelector('.d-to').value}))}
function submitModal(e,type,id){e.preventDefault();const data=Object.fromEntries(new FormData(e).entries());data.id=id?Number(id):Date.now();if(type==='clinics'){const clinicId=data.id;const doctors=collectDoctorRows();const existingDoctorIds=db.doctors.filter(d=>Number(d.clinicId)===clinicId).map(d=>d.id);if(id){db.doctors=db.doctors.filter(d=>Number(d.clinicId)!==clinicId);doctors.forEach((d,i)=>db.doctors.push({...d,id:existingDoctorIds[i]||Date.now()+i,clinicId}));}else{doctors.forEach((d,i)=>db.doctors.push({...d,id:Date.now()+i,clinicId}));}delete data.id;data.id=clinicId;db.clinics[id?db.clinics.findIndex(c=>c.id===clinicId):db.clinics.length]={...data};if(!id&&db.clinics[db.clinics.length-1].id!==clinicId)db.clinics[db.clinics.length-1].id=clinicId;}else{if(type==='services')data.price=String(Number(data.price));if(type==='doctors')data.clinicId=Number(data.clinicId);if(type==='services')data.clinicId=Number(data.clinicId);if(id){const i=db[type].findIndex(x=>x.id===Number(id));db[type][i]=data}else db[type].push(data)}save();closeModal();render()}
function closeModal(){document.getElementById('dataModal')?.remove()}
function escapeAttr(s=''){return escapeHtml(String(s)).replace(/\n/g,'&#10;').replace(/\r/g,'&#13;')}
function addItem(type){openModal(type)}
function editItem(type,id){openModal(type,id)}
function removeItem(type,id){if(confirm('حذف هذا العنصر؟')){db[type]=db[type].filter(x=>x.id!==id);save();render()}}
function chat(c){c.innerHTML=`<div class="chat"><div class="messages" id="msgs"><div class="msg bot">أهلًا بحضرتك. أنا المساعد الافتراضي لـ${db.center.name}. أقدر أساعدك في معرفة العيادات، الأطباء، الأسعار ومواعيد العمل.</div></div><div class="chatbar"><input id="q" placeholder="اكتب سؤالك هنا..."><button class="primary" onclick="send()">إرسال</button></div></div>`;q.onkeydown=e=>{if(e.key==='Enter')send()}}
function answer(q){q=q.toLowerCase();if(q.includes('سعر')||q.includes('كشف')||q.includes('فلوس'))return 'أسعار الكشف: '+db.clinics.map(x=>`${x.name}: ${x.price} جنيه`).join(' — ');if(q.includes('مواعيد')||q.includes('فاتح')||q.includes('عمل'))return `مواعيد المركز: ${db.center.hours}`;if(q.includes('عياد'))return 'العيادات المتاحة: '+db.clinics.map(x=>x.name).join('، ');if(q.includes('دكتور')||q.includes('طبيب'))return db.doctors.map(x=>`${x.name} — ${x.specialty} — ${x.days} — ${x.time}`).join('\n');for(const f of db.faqs)if(q.includes(f.q.slice(0,6).toLowerCase()))return f.a;return 'أقدر أساعدك في العيادات، الأطباء، الأسعار ومواعيد العمل. ولو سؤالك يحتاج موظفًا، أقدر أحوّل المحادثة للاستقبال.'}
function send(){let v=q.value.trim();if(!v)return;let m=$('#msgs');m.innerHTML+=`<div class="msg user">${escapeHtml(v)}</div><div class="msg bot">${escapeHtml(answer(v)).replaceAll('\n','<br>')}</div>`;q.value='';m.scrollTop=m.scrollHeight}function escapeHtml(s){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}render();